name: nextrelease
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [labeled, unlabeled, edited, synchronize]

jobs:
  sync:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' && github.head_ref == 'nextrelease' }}
    runs-on: ubuntu-latest
    steps:
    - run: npm install -g heroku
    - uses: dropseed/nextrelease@v2
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.DROPSEED_PYPI_TOKEN }}
      with:
        prepare_cmd: |
          sed -i -e "s/version = \"[^\"]*\"$/version = \"$VERSION\"/g" buildpack.toml
        publish_cmd: |
          heroku buildpacks:publish forgepackages/forge $TAG
        github_token: ${{ secrets.GITHUB_TOKEN }}
